---
version: "2.0"

services:
  app:
    image: deadblackclover/evmos:0.2.1
    env:
     - "ROOT_PASS=" # Root password for SSH connection
     - "MONIKER=CipherDogs" # Node name
     - "MNEMONIC=" # Mnemonic phrase
     - "WALLET_NAME=node" # Wallet name
     - "WALLET_PASS=" # Wallet password

     - "EVMOS_VER=v5.0.0"
     - "GENESIS=https://github.com/evmos/testnets/raw/main/evmos_9000-4/genesis.zip"
     - "ADDRBOOK="
     - "PEERS=3a6b22e1569d9f85e9e97d1d204a1c457d860926@bd-evmos-testnet-seed-node-01.bdnodes.net:26656"
     - "SEEDS=3a6b22e1569d9f85e9e97d1d204a1c457d860926@bd-evmos-testnet-seed-node-01.bdnodes.net:26656"

     - "DENOM=atevmos"
     - "CHAIN_ID=evmos_9000-4"
     - "MINIMUM_GAS_PRICES=25000000000"

     - "SELF_BONDED=true"

     - "CREATE_VALIDATOR_GAS=500000"
     - "CREATE_VALIDATOR_FEES=12500000000000000"

     - "LINK_KEY=" # Link to the posted pirv-validator_key.json (direct download). It will also work from other Cosmos-based testnets
     - "SNAPSHOT_LINK="
     - "SYNC_RPC=https://evmos-testnet-rpc.polkachu.com:443"
    expose:
      - port: 26657
        as: 80
        to:
          - global: true
      - port: 26656
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 8
        memory:
          size: 32Gi
        storage:
          size: 100Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        app:
          denom: uakt
          amount: 1000
deployment:
  app:
    akash:
      profile: node
      count: 1